server:
  port: 8888
  file: userManager.log

spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course?serverTimezone=GMT
    username: root
    password: 123456

mybatis:
  type-alias-package: com.course.model
  mapper-locations:
    - mapper/*